apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green-canary
  name: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-canary
  template:
    metadata:
      labels:
        app: blue-green-canary
        group: bgc
        version: <will be updated>
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: <will be updated>
          image: quay.io/rhdevelopers/blue-green-canary
          imagePullPolicy: Always
          env:
            - name: BLUE_GREEN_CANARY_COLOR
              value: "#000"
            - name: BLUE_GREEN_CANARY_MESSAGE
              value: "Not Updated"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ready
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 2
